### ISSUE TITLE
OpenVSX Publishing?

### ISSUE THREAD

**Issue by agnosticlines** [mnespor/vscode-color-identifiers-mode#6]
Hey there!

I absolutely love this extension, but I have a small request, would it be possible for you to publish it to the OpenVSX Marketplace? Docs on how to do so are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

I can use it fine on my desktop but some of my friends who use web based IDEs like GitPod are unable to as they don’t have the official MS marketplace :(

Thank you!

**Comment by mnespor** [comment]
Hi there. I've had a busy couple of weeks, but I had a chance to publish tonight. The extension is available here: https://open-vsx.org/extension/MatthewNespor/vscode-color-identifiers-mode

Thanks for the message, and I'm glad you're enjoying the extension!

**Comment by agnosticlines** [comment]
Not a problem! I am, do you have anywhere to donate? It’s such a simple extension but it makes reading code so much easier, and I’ve been missing it since I retired my emacs config

Thank you so much for assisting!
