### ISSUE TITLE
not working for me in Go and I don't know how to debug this

### ISSUE THREAD

**Issue by seebs** [mnespor/vscode-color-identifiers-mode#7]
Hi! I'm trying this out, and after a bit of study, I've concluded that it works for me in Python and Clojure, but in Go, I just get all identifiers white. I don't know enough of what's going on to usefully debug this. I have a Go language server installed and it seems to work for other purposes (like looking up docs). I've experimentally added most of the tokenKinds to the list of token kinds, which seems not to change anything. I don't understand vscode extensions well enough to know how to proceed from here. I assume I'd want to check whether given tokens were being identified at all, and if so with what type, maybe?

**Comment by seebs** [comment]
answer: `"gopls": { "ui.semanticTokens": true }`

**Comment by mnespor** [comment]
Glad to hear! In case it helps, this extension uses the list of tokens exposed to the [vscode.provideDocumentSemanticTokens](https://code.visualstudio.com/api/references/commands) command by the language server.
